services:
  postgres_dev:
    image: postgres:17
    container_name: auth_postgres_dev
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dev_net

  pgadmin_dev:
    image: dpage/pgadmin4
    container_name: auth_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_COOKIE_NAME: "'pgadmin_session_dev'"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    ports:
      - "5050:80"
    networks:
      - dev_net

volumes:
  postgres_dev_data:

networks:
  dev_net:
